#!/bin/bash

if getent group vboxusers > /dev/null; then
    for user in $(getent group vboxusers | cut -d: -f4 | tr ',' ' '); do
        gpasswd -d "${user}" vboxusers
    done
    groupdel vboxusers
fi

rmmod vboxnetflt vboxnetadp vboxdrv