#!/usr/bin/env bash

# Update system branding
sed -i 's|^Manjaro Linux|BigCommunity|g' /etc/issue

# Update os-release
sed -i 's|^ *\bNAME\b *=.*|NAME="BigCommunity"|' /usr/lib/os-release
sed -i 's|^ *\bPRETTY_NAME\b *=.*|PRETTY_NAME="BigCommunity"|' /usr/lib/os-release
sed -i 's|^ *\bHOME_URL\b *=.*|HOME_URL="https://communitybig.org"|' /usr/lib/os-release
sed -i 's|^ *\bDOCUMENTATION_URL\b *=.*||' /usr/lib/os-release
sed -i 's|^ *\bSUPPORT_URL\b *=.*|SUPPORT_URL="https://t.me/BigLinuxCommunity"|' /usr/lib/os-release
sed -i 's|^ *\LOGO\b *=.*|LOGO="comm-menu"|' /usr/lib/os-release
sed -i 's|^ *\ID\b *=.*|ID="biglinux"|' /usr/lib/os-release
sed -i 's|^ *\bBUG_REPORT_URL\b *=.*|BUG_REPORT_URL="https://github.com/communitybig"|' /usr/lib/os-release
sed -i 's|^ *\bPRIVACY_POLICY_URL=.*||' /usr/lib/os-release

# Create symlink for os-release
[[ -e /usr/lib/os-release ]] && ln -sf /usr/lib/os-release /etc/os-release

# Remove 'Linux' from name where it appears
sed -i 's|BigCommunity Linux|BigCommunity|g' /etc/issue
sed -i 's|BigCommunity Linux|BigCommunity|g' /usr/lib/os-release
