#!/bin/bash

if ! getent group vboxusers > /dev/null; then
    groupadd vboxusers
fi

for user in $(awk -F':' '{ if ($3 >= 1000 && $1 != "nobody") print $1 }' /etc/passwd); do
    gpasswd -a "${user}" vboxusers
done

vboxreload